version: 1.0.{build}
before_build:
- cmd: nuget restore DtoGen\DtoGen.sln
- cmd: nuget restore JsonClassGenerator.sln
build:
  project: DtoGen\DtoGen.sln
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: 0FpRSIDupGKBPYAu9Kq0yG/fQnpMuyCbgegXLtMi/dADgLx44W01Y7EQtsz7kONh
after_test:
- cmd: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.2.1\tools\nunit3-console.exe" -targetargs:"/domain:single JsonClassGenerator.Tests\bin\debug\JsonClassGenerator.Tests.dll" -output:coverage.xml
- cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
artifacts:
  - path: 'DtoGen\DtoGen\DtoGen\bin\Debug\*.dll'
    name: release-deploy